### ISSUE TITLE
Lofty claims, but no documentation

### ISSUE THREAD

**Issue by stugol** [taijiweb/taijilang#1]
> more useful macro than in lisp, more important white space than in python, more general preprocess than in C, more powerful meta compilation than in metalua, more flexible dialect than in rebol, more optimized object code than in coffee-script...

These are impressive claims. But without a single scrap of documentation to be found anywhere, utterly meaningless.

Not to mention that development seems to have stalled.

**Comment by taijiweb** [comment]
Thank you for your comment on this project. It's a pity that I'm working on another project and have no time to continue this project.
